version: '2'
services:
    server:
        build: server
        volumes:
            - ./srv:/srv
        ports:
            - 0.0.0.0:8080:80
            - 0.0.0.0:8443:443
    frontend:
        image: webpack
        build:
            context: ./frontend
        ports:
            - 8080:8080
        volumes:
            - ./frontend:/bindmount:rw
            - node_modules:/src/node_modules
    instagrabber:
        image: stealthii/instagrabber
        volumes:
            - ./srv:/srv
        environment:
            CLIENT_ID: "e57454d58e8a43b5b1e523b0016e42d1"
            CLIENT_SECRET: "2be7470623f54bb98d3f1ebe86299ed1"
            TAG_NAME: "rehabstudio"
            OUTPUT_DIR: "/assets/instagram_photos"
            REFRESH_INTERVAL: 15

volumes:
    cache-data:
        driver: local
    node_modules:
        driver: local
