version: '2'
services:
    server:
        build: server
        volumes:
            - ./srv:/srv
        ports:
            - 0.0.0.0:8080:80
            - 0.0.0.0:8443:443
volumes:
    cache-data:
        driver: local
