var Datas = {
    shapes: [
        {
            points: [
                {x:-250, y:-270},
                {x:-251, y:-271},
                {x:-110, y:200},
                {x:390, y:100}
            ]
        },{
            points: [
                {x:-280, y:-170},
                {x:-160, y:80},
                {x:300, y:250},
                {x:70, y:-120}
            ]
        },{
            points: [
                {x:-200, y:-160},
                {x:-100, y:260},
                {x:300, y:80},
                {x:220, y:-90}
            ]
        },{
            points: [
                {x:-180, y:-110},
                {x:-60, y:260},
                {x:200, y:50},
                {x:120, y:-250}
            ]
        },
        {
            points: [
                {x:-220, y:-230},
                {x:-221, y:-231},
                {x:30, y:200},
                {x:390, y:100}
            ]
        },{
            points: [
                {x:-200, y:-160},
                {x:-100, y:160},
                {x:160, y:180},
                {x:220, y:-90}
            ]
        }
    ],
    names: [
        'iAmDavis',
        'DEVEXER',
        'beth2daniel',
        'TatchuWispar',
        'EkoGrandeTV',
        'sina_111',
        'donttrusthacker',
        'JuiceticeTV',
        'AirAngel_tv',
        'BlueManc',
        'AuscrewTV',
        'jeffgeophph',
        'clearunmarketing',
        'IchNixAhnung',
        'Squidgeneer',
        'Zepptimus',
        'YpnotiS',
        'PENchanter22',
        'cid380',
        'TheNVGOW',
        'Arielote',
        'jmanweezel',
        '4kays',
        'skittzipoo',
        'HelHathSomeFury',
        'Nj_55',
        'njmcode',
        'Peatthegreat',
        'Rockyyy_',
        'ainevixen',
        'JordanDH',
        'Snuudles',
        'D3anTV',
        'Turonah',
        'lottiieeee',
        'Asparagun',
        'SecularMoralist',
        'obiwankenobi_gamer',
        'mrjlawes1994',
        'wolf_thunderr_',
        'Welindor',
        'Lowveg',
        'Dinxist',
        'KillaGuy655',
        'salamimeats',
        'TheCalvinist',
        'TheBrambles',
        'Umbra_Tsubaki',
        '01HotSpot01',
        'CPTberio',
        'ellis6644',
        'Nemulli',
        'not_han',
        'iaksas',
        'Frost_Bytes',
        'orcmarine91',
        'Amethystkorn',
        'zenofury23',
        'TheDeadeyeDoc',
        'Talchi_nw',
        'dejaboo7',
        'FryZerBuRn',
        'mamorin',
        'Everyday_Gaymer',
        'yelnats1271',
        'DinckelMan',
        'starbits',
        'mrbleph',
        'Arrowmasta',
        'ShadowWolfQc',
        'MorrowindInMySails',
        'DadsOffDuty',
        'davefmv',
        'jtaps',
        'Davinoth',
        'maya_the_mirb',
        'MagicalGirlRooney',
        'Wmoore1982',
        'Pink_harmonica',
        'Boom____Boom',
        'clockworksimon',
        'messyhair',
        'Green_Leader87',
        'Symastus',
        'Pitta_ecr',
        'allieraee',
        'Danyaal263',
        'canman_o7',
        'MisterPixelzz',
        'kraftpunkbot',
        'Pyrocleptic',
        'dto249325',
        'melodicdistress',
        'kitiko_c',
        'LazyLJ',
        'unicolan',
        'motherrmoon',
        'WXLyfe',
        'MFCthatsme',
        'JustRuff',
        'macc_cubeyyscat',
        'cmdr_r0l0',
        'hursheybot',
        'nyxuna',
        'Ya_Its_The_D',
        'RandleTheAnimal',
        'b1___',
        'amackert',
        'KingDime',
        'CaptainSuperRanger',
        'XilentFlex',
        'RelicElek',
        'jotun23',
        'retronugget5632',
        'susakobunny',
        'SenorCrumpets',
        'yalbet',
        'CubeyyGaming',
        'timidtheresa',
        'Zelki13',
        'mateossh',
        'RenderTechUK',
        'Peppah',
        'cowboybimb0',
        'JNorrington',
        'zygis1996',
        'Nomezilla',
        'TunaManPlays',
        'Razzereign',
        'LewdOtter',
        'TazZ_WoodZ',
        'rabbibacon',
        'vinno_the_squire',
        'WeHaveZa',
        'Shamm_B',
        'beardedmug',
        'VikingPrincess1',
        'schlimsicle',
        'LanyDelRey',
        'MarcMush',
        'Zoltaris',
        'irishpandaren',
        'mr_kyle0210',
        'Armycam98',
        'Lionheart817',
        'Koopa_Squad',
        'Ryan_Hansen',
        'Coi5o',
        'jesskimosa',
        'thenorseguy',
        'MagicalMinish',
        'TwilekBathRelaxer',
        'breyy88',
        'RadRosie',
        'MisterJimmyJam',
        'SinfulArte',
        'thekeeperofflame',
        'CrystalPistal',
        'Coffee4Joe',
        'PowerClipper',
        'SpudTheOtter',
        'hyliandreams93',
        'drag0ntales420',
        'AffinityChris',
        'UforiK',
        'Kaykrisify',
        'Swerv3xknapp',
        'eddievasellini',
        '1nsanecl0wn',
        'Yawwn_Solo',
        'sparkhive',
        'KokiriGnome',
        'Die_Guy',
        'NOON3RS',
        'Ivory_Torea',
        'justin24',
        'dr_potatoz',
        'BTG_Siouxper',
        'Connlocks',
        'Neck_Twist',
        'Helliphino',
        'honeybri_',
        'mischacrossing',
        'jeselaine',
        'SpookyAri',
        'StrehFox',
        'goldneye00agent',
        'EvenDawn',
        'HursheyCrisp',
        'shelltek35',
        'jessyyyyb',
        'skylar_mitchell101',
        'thund3rb0y21',
        'SpookyKandy',
        'MrJakeWoof',
        'supersasquatch1993',
        'Onariko',
        'coulteh',
        'ow_fish',
        'SquashCT',
        'thegrieve',
        'YerGirlSa',
        'darklinkx1991',
        'SquishieInc',
        'itsDefrag',
        'Young_Scott',
        'TostiTom',
        'Rovefogle',
        'jimb0',
        'Nafferoni',
        'CommonTater4U',
        'HAL451',
        'Slunks',
        'Mitsuneto',
        'Aroy',
        'Consoletation',
        'theBryanBoru',
        'HoneyTheLewdBadger',
        'realstreamersupport',
        'clairebones',
        'FarsetLabs'
    ]
}

module.exports = Datas;
